# Generated by Django 3.2.2 on 2021-05-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagefield', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetImage',
        ),
    ]
